
package com.siebel.customui;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTS_spcWebService", targetNamespace = "http://siebel.com/CustomUI", wsdlLocation = "file:/C:/ASiebelWSTelegram.WSDL")
public class MTSSpcWebService_Service
    extends Service
{

    private final static URL MTSSPCWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTSSPCWEBSERVICE_EXCEPTION;
    private final static QName MTSSPCWEBSERVICE_QNAME = new QName("http://siebel.com/CustomUI", "MTS_spcWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ASiebelWSTelegram.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTSSPCWEBSERVICE_WSDL_LOCATION = url;
        MTSSPCWEBSERVICE_EXCEPTION = e;
    }

    public MTSSpcWebService_Service() {
        super(__getWsdlLocation(), MTSSPCWEBSERVICE_QNAME);
    }

    public MTSSpcWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTSSPCWEBSERVICE_QNAME, features);
    }

    public MTSSpcWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, MTSSPCWEBSERVICE_QNAME);
    }

    public MTSSpcWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTSSPCWEBSERVICE_QNAME, features);
    }

    public MTSSpcWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTSSpcWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MTSSpcWebService
     */
    @WebEndpoint(name = "MTS_spcWebService")
    public MTSSpcWebService getMTSSpcWebService() {
        return super.getPort(new QName("http://siebel.com/CustomUI", "MTS_spcWebService"), MTSSpcWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTSSpcWebService
     */
    @WebEndpoint(name = "MTS_spcWebService")
    public MTSSpcWebService getMTSSpcWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://siebel.com/CustomUI", "MTS_spcWebService"), MTSSpcWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTSSPCWEBSERVICE_EXCEPTION!= null) {
            throw MTSSPCWEBSERVICE_EXCEPTION;
        }
        return MTSSPCWEBSERVICE_WSDL_LOCATION;
    }

}
